### ISSUE TITLE
Integer values fail to translate with YML input

### ISSUE THREAD

**Issue by einzige** [midwire/tr4n5l4te#15] opened 2020-04-04 14:37 UTC
Happens when running console command to translate yaml file:

```bash
translate -y project/config/locales/pages/pages/en.yml -l Portuguese
```

Sometimes translations *contain integer* values, eg :

price: 250

it fails with `RuntimeError`:

```
Traceback (most recent call last):
	30: from /Users/szinin/.rbenv/versions/2.5.3/bin/translate:23:in `<main>'
	29: from /Users/szinin/.rbenv/versions/2.5.3/bin/translate:23:in `load'
	28: from /Users/szinin/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/tr4n5l4te-0.1.9/exe/translate:10:in `<top (required)>'
	27: from /Users/szinin/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/tr4n5l4te-0.1.9/lib/tr4n5l4te/runner.rb:33:in `run'
	26: from /Users/szinin/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/tr4n5l4te-0.1.9/lib/tr4n5l4te/runner.rb:42:in `process'
	25: from /Users/szinin/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/tr4n5l4te-0.1.9/lib/tr4n5l4te/runner.rb:42:in `each_with_object'
	24: from /Users/szinin/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/tr4n5l4te-0.1.9/lib/tr4n5l4te/runner.rb:42:in `each'
	23: from /Users/szinin/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/tr4n5l4te-0.1.9/lib/tr4n5l4te/runner.rb:44:in `block in process'
	22: from /Users/szinin/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/tr4n5l4te-0.1.9/lib/tr4n5l4te/runner.rb:42:in `process'
	21: from /Users/szinin/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/tr4n5l4te-0.1.9/lib/tr4n5l4te/runner.rb:42:in `each_with_object'
	20: from /Users/szinin/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/tr4n5l4te-0.1.9/lib/tr4n5l4te/runner.rb:42:in `each'
	19: from /Users/szinin/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/tr4n5l4te-0.1.9/lib/tr4n5l4te/runner.rb:44:in `block in process'
	18: from /Users/szinin/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/tr4n5l4te-0.1.9/lib/tr4n5l4te/runner.rb:42:in `process'
	17: from /Users/szinin/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/tr4n5l4te-0.1.9/lib/tr4n5l4te/runner.rb:42:in `each_with_object'
	16: from /Users/szinin/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/tr4n5l4te-0.1.9/lib/tr4n5l4te/runner.rb:42:in `each'
	15: from /Users/szinin/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/tr4n5l4te-0.1.9/lib/tr4n5l4te/runner.rb:44:in `block in process'
	14: from /Users/szinin/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/tr4n5l4te-0.1.9/lib/tr4n5l4te/runner.rb:42:in `process'
	13: from /Users/szinin/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/tr4n5l4te-0.1.9/lib/tr4n5l4te/runner.rb:42:in `each_with_object'
	12: from /Users/szinin/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/tr4n5l4te-0.1.9/lib/tr4n5l4te/runner.rb:42:in `each'
	11: from /Users/szinin/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/tr4n5l4te-0.1.9/lib/tr4n5l4te/runner.rb:44:in `block in process'
	10: from /Users/szinin/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/tr4n5l4te-0.1.9/lib/tr4n5l4te/runner.rb:42:in `process'
	 9: from /Users/szinin/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/tr4n5l4te-0.1.9/lib/tr4n5l4te/runner.rb:42:in `each_with_object'
	 8: from /Users/szinin/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/tr4n5l4te-0.1.9/lib/tr4n5l4te/runner.rb:42:in `each'
	 7: from /Users/szinin/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/tr4n5l4te-0.1.9/lib/tr4n5l4te/runner.rb:44:in `block in process'
	 6: from /Users/szinin/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/tr4n5l4te-0.1.9/lib/tr4n5l4te/runner.rb:42:in `process'
	 5: from /Users/szinin/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/tr4n5l4te-0.1.9/lib/tr4n5l4te/runner.rb:42:in `each_with_object'
	 4: from /Users/szinin/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/tr4n5l4te-0.1.9/lib/tr4n5l4te/runner.rb:42:in `each'
	 3: from /Users/szinin/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/tr4n5l4te-0.1.9/lib/tr4n5l4te/runner.rb:44:in `block in process'
	 2: from /Users/szinin/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/tr4n5l4te-0.1.9/lib/tr4n5l4te/runner.rb:52:in `translate'
	 1: from /Users/szinin/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/tr4n5l4te-0.1.9/lib/tr4n5l4te/translator.rb:17:in `translate'
/Users/szinin/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/tr4n5l4te-0.1.9/lib/tr4n5l4te/translator.rb:51:in `validate_and_encode': Cannot translate a [Integer]: '250' (RuntimeError)
```

**Comment by midwire** [comment] 2020-04-28 19:13
Thanks @einzige - working on this today.  Sorry it has taken me so long to get to it.

**Comment by midwire** [comment] 2020-04-28 19:18
@einzige can you provide a sample of the YML file that fails?  In my testing it seems to be translating integers OK.

**Comment by midwire** [comment] 2020-05-12 14:53
Closing this because I cannot reproduce the problem.

**Closed by midwire** 2020-05-12 14:53 UTC
