### ISSUE TITLE
Unknown Keyword Error

### ISSUE THREAD

**Issue by Kovalski4** [midwire/tr4n5l4te#27] opened 2021-06-16 11:04 UTC
### Expected Behavior
I try to translate english yml file to turkish yml file but its throw that error

### Steps to reproduce the problem

---
* Current Version: 
* Operating System: 
![Ekran Alıntısı](https://user-images.githubusercontent.com/49496860/122208241-bbc65980-ceab-11eb-9b74-6f2e5bedb2b4.PNG)

**Comment by midwire** [comment] 2021-06-16 23:08
@Kovalski4 are you able to provide the source `en.yml` file that you are using?  It looks like you are using a Windows subsystem version of Linux, so can you also provide which version of the `psych` gem is installed.

**Comment by midwire** [comment] 2022-09-06 15:25
Closing this without further information to reproduce the problem

**Closed by midwire** 2022-09-06 15:25 UTC
